export enum SUBSCRIPTION_KEYS {
  NEW_TEMPERATURE_READING = 'NEW_TEMPERATURE_READING',
  VESSEL_BURNER_CHANGE = 'VESSEL_BURNER_CHANGE',
  PUMP_ACTIVE_CHANGE = 'PUMP_ACTIVE_CHANGE',
  NEW_FERMENT_READING = 'NEW_FERMENT_READING',
}
